### ISSUE TITLE
Test situation

### ISSUE THREAD

**Issue by cowrturn** [DACUS1995/pytorch-mmap-dataset#2]
When I was testing with 1106 images of size 512*512, I found that In memory benchmark, the efficiency is much faster than pytorch-mmap, can you explain the advantage of pytorch-mmap over In memory benchmark? @DACUS1995

**Comment by cowrturn** [comment]
![image](https://github.com/DACUS1995/pytorch-mmap-dataset/assets/24434966/dccee900-9ea4-401f-a7dd-eaeca4a36ad6)

**Comment by cowrturn** [comment]
![image](https://github.com/DACUS1995/pytorch-mmap-dataset/assets/24434966/c163723b-02b4-4797-af57-c80935e0edb5)

**Comment by cowrturn** [comment]
[benchmark.zip](https://github.com/DACUS1995/pytorch-mmap-dataset/files/12449979/benchmark.zip)
Here's my test based on your code, to make it easier to check, I'll send it to you as well

**Comment by DACUS1995** [comment]
For an allocation that can physically fit in memory, data access will always be faster than mmap. The advantage of using a mmap approach only comes to light when the size of the data far exceeds the limits of your RAM. Didn't have time to look over the code, but from this information, the performance is more or less as expected.
